### ISSUE TITLE
pepper.py cannot be run

### ISSUE THREAD

**Issue by Th3F0x-code** [Th3Hurrican3/PEpper#4]
every time I try to run it this error comes up

Traceback (most recent call last):
  File "pepper.py", line 5, in <module>
    from modules import run
  File "/home/thefox/Scrivania/tools/Analysis/PEpper/modules/run.py", line 12, in <module>
    from modules import yarar
  File "/home/thefox/Scrivania/tools/Analysis/PEpper/modules/yarar.py", line 1, in <module>
    import yara
  File "/home/thefox/.local/lib/python3.7/site-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/home/thefox/.local/lib/python3.7/site-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/home/thefox/.local/lib/python3.7/site-packages/yara/libyara_wrapper.py", line 362, in <module>
    libyaradll.lookup_rule.restype = POINTER(RULE)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libyara.so: undefined symbol: lookup_rule

**Comment by ActorExpose** [comment]
Ive got something like this....



Traceback (most recent call last):
  File "/Users/Kyfx/Desktop/PEpper-master/pepper.py", line 5, in <module>
    from modules import run
  File "/Users/Kyfx/Desktop/PEpper-master/modules/run.py", line 1, in <module>
    from modules import metadata
  File "/Users/Kyfx/Desktop/PEpper-master/modules/metadata.py", line 1, in <module>
    import magic
  File "/usr/local/lib/python3.9/site-packages/magic/__init__.py", line 208, in <module>
    libmagic = loader.load_lib()
  File "/usr/local/lib/python3.9/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation


Trying to find a version to run for "libmagic"
